"""Durable, atomic daily quota for replies generated by neurochat."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

from sqlalchemy import text

from database.repository import db
from database.sqlite_pragmas import run_with_busy_retry


@dataclass
class ReplyReservation:
    mailing_id: int
    local_date: str
    engine: object = field(repr=False)
    _state: str = field(default="pending", init=False, repr=False)

    async def refresh_for_send(self, *, now: datetime | None = None) -> bool:
        """Move the slot if the local date changed during LLM/typing delay."""
        if self._state != "pending":
            return False
        instant = now or datetime.now(timezone.utc)
        if instant.tzinfo is None:
            raise ValueError("now must have timezone")

        async def move_once():
            async with self.engine.begin() as conn:
                await conn.exec_driver_sql("BEGIN IMMEDIATE")
                row = (await conn.execute(text(
                    "SELECT neuro_daily_reply_limit, neuro_timezone FROM mailings WHERE id=:id"
                ), {"id": self.mailing_id})).one_or_none()
                if row is None:
                    return False, None
                local_date = instant.astimezone(ZoneInfo(row[1] or "UTC")).date().isoformat()
                if local_date == self.local_date:
                    limit = int(row[0] or 0)
                    if limit:
                        counts = (await conn.execute(text(
                            "SELECT sent_count, reserved_count FROM neuro_reply_daily_usage "
                            "WHERE mailing_id=:mailing_id AND local_date=:local_date"
                        ), {"mailing_id": self.mailing_id, "local_date": local_date})).one_or_none()
                        if counts is None or counts[0] + counts[1] > limit:
                            return False, None
                    return True, None
                await conn.execute(text(
                    "INSERT OR IGNORE INTO neuro_reply_daily_usage "
                    "(mailing_id, local_date, sent_count, reserved_count) "
                    "VALUES (:mailing_id, :local_date, 0, 0)"
                ), {"mailing_id": self.mailing_id, "local_date": local_date})
                result = await conn.execute(text(
                    "UPDATE neuro_reply_daily_usage SET reserved_count=reserved_count+1 "
                    "WHERE mailing_id=:mailing_id AND local_date=:local_date "
                    "AND (:limit=0 OR sent_count+reserved_count<:limit)"
                ), {"mailing_id": self.mailing_id, "local_date": local_date,
                    "limit": int(row[0] or 0)})
                if result.rowcount != 1:
                    return False, None
                old = await conn.execute(text(
                    "UPDATE neuro_reply_daily_usage SET reserved_count=reserved_count-1 "
                    "WHERE mailing_id=:mailing_id AND local_date=:local_date "
                    "AND reserved_count>0"
                ), {"mailing_id": self.mailing_id, "local_date": self.local_date})
                if old.rowcount != 1:
                    raise RuntimeError("neuro reply reservation missing during date change")
                return True, local_date

        allowed, new_date = await run_with_busy_retry(move_once, op_name="neuro-reply-refresh")
        if new_date is not None:
            self.local_date = new_date
        return allowed

    async def mark_sent(self) -> None:
        """Call immediately after Telegram confirms a text or link send."""
        if self._state != "pending":
            return
        # A failed database write must retain the reservation. Never release a
        # slot after Telegram has already accepted the message.
        self._state = "sent"
        async def update_count():
            async with self.engine.begin() as conn:
                result = await conn.execute(text(
                    "UPDATE neuro_reply_daily_usage SET reserved_count=reserved_count-1, "
                    "sent_count=sent_count+1 WHERE mailing_id=:mailing_id "
                    "AND local_date=:local_date AND reserved_count>0"
                ), {"mailing_id": self.mailing_id, "local_date": self.local_date})
                if result.rowcount != 1:
                    raise RuntimeError("neuro reply reservation missing after Telegram send")
        await run_with_busy_retry(update_count, op_name="neuro-reply-sent")

    async def release(self) -> None:
        if self._state != "pending":
            return
        self._state = "released"
        async def update_count():
            async with self.engine.begin() as conn:
                await conn.execute(text(
                    "UPDATE neuro_reply_daily_usage SET reserved_count=reserved_count-1 "
                    "WHERE mailing_id=:mailing_id AND local_date=:local_date "
                    "AND reserved_count>0"
                ), {"mailing_id": self.mailing_id, "local_date": self.local_date})
        await run_with_busy_retry(update_count, op_name="neuro-reply-release")


async def reserve_reply(
    mailing_id: int, *, now: datetime | None = None, engine=None
) -> ReplyReservation | None:
    """Reserve one slot before any LLM call; None means the day is full.

    BEGIN IMMEDIATE serializes both the live mailing settings read and the
    counter update among SQLite connections/processes. A crash may leave a
    reservation counted until that local date ends, which fails closed.
    """
    engine = engine or db.engine
    if engine is None:
        raise RuntimeError("database is not connected")
    instant = now or datetime.now(timezone.utc)
    if instant.tzinfo is None:
        raise ValueError("now must have timezone")
    async def reserve_once():
        async with engine.begin() as conn:
            # Scoped to this tiny reservation transaction; unlike a global
            # IMMEDIATE mode, other reads and normal writes remain unchanged.
            await conn.exec_driver_sql("BEGIN IMMEDIATE")
            row = (await conn.execute(text(
                "SELECT neuro_daily_reply_limit, neuro_timezone FROM mailings WHERE id=:id"
            ), {"id": mailing_id})).one_or_none()
            if row is None:
                return None
            limit = int(row[0] or 0)
            local_date = instant.astimezone(ZoneInfo(row[1] or "UTC")).date().isoformat()
            await conn.execute(text(
                "INSERT OR IGNORE INTO neuro_reply_daily_usage "
                "(mailing_id, local_date, sent_count, reserved_count) "
                "VALUES (:mailing_id, :local_date, 0, 0)"
            ), {"mailing_id": mailing_id, "local_date": local_date})
            result = await conn.execute(text(
                "UPDATE neuro_reply_daily_usage SET reserved_count=reserved_count+1 "
                "WHERE mailing_id=:mailing_id AND local_date=:local_date "
                "AND (:limit=0 OR sent_count+reserved_count<:limit)"
            ), {"mailing_id": mailing_id, "local_date": local_date, "limit": limit})
            if result.rowcount != 1:
                return None
        return ReplyReservation(mailing_id, local_date, engine)

    return await run_with_busy_retry(reserve_once, op_name="neuro-reply-reserve")
